name: IronGolem
version: '1.0-SNAPSHOT'
main: winlyps.ironGolem.IronGolem
api-version: '1.20'
authors: [ Winlyps ]
description: A plugin that provides a special egg to summon Iron Golems.
commands:
  irongolem:
    description: Gives the player a special egg to summon an Iron Golem.
    usage: /irongolem